[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[build.environment]
 SECRETS_SCAN_OMIT_PATHS = "isan1ib/index.html,isan1ib/login.html,isat1ia/login.html,isat1ia/lestextar,isat1ia/hlustun,isat1ia/spjall,isat1ia/hljodritun,isat1ia/leikir"
